### ISSUE TITLE
Generate GraphQL scheme from JSON Api

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [redound/graphql-ide#12]
@olivierandriessen This is a really good tool, but I was wondering if you can add support for importing json and then auto generate GrapghQL scheme using https://github.com/Aweary/json-to-graphql I wanted to use this tool for mocking API's

http://graphql.org/blog/mocking-with-graphql/

**Comment by olivierandriessen** [comment]
@Ashraf-Ali-aa. Sounds interesting, I'm not sure what your idea is. Could you give a more detailed example of what you have in mind?

**Comment by Ashraf-Ali-aa** [comment]
@olivierandriessen We got some Rest API and it's very tedious to modify the data for UI Automation due to heavily nested elements in the JSON. I was thinking of using GraphQL generate Mock JSON data, but in order to do that, we would require creating a GraphQL Scheme and populating the JSON with predefined data.

The predefined data would be scrapped off the JSON API when the GraphQL Scheme from the JSON and stored in a database, Also if we pass in a new URL to the tool which has the same GraphQL Scheme it would update the database with the new data from the API's. using this approach you could create an instant mock server using real data the could be manipulated using the GraphQL IDE

**Comment by Ashraf-Ali-aa** [comment]
@olivierandriessen I have found a better way to convert Rest Api's to GraphQl, but it would be use full in the IDE to import the GraphQl Schema via http url. 
https://github.com/yarax/swagger-to-graphql

**Comment by olivierandriessen** [comment]
@Ashraf-Ali-aa Although it sounds like a great solution for the problem your trying to solve, this goes beyond the scope of this application. In your last comment you mentioned you want to import the GraphQL schema using a http endpoint, this is where this app is for. If your GraphQL server complies to the GraphQL specification you should be able to use this app.
