### ISSUE TITLE
release app for 1.1.0

### ISSUE THREAD

**Issue by karmajunkie** [redound/graphql-ide#13]
I believe the Mac OS binary version listed under the 1.1.0 release is actually the 1.0.0 release.

When I download the OS X version under 1.1.0, I'm seeing the behavior associated with 1.0.0 (i.e. not using environment headers on the requests) and the About box shows the version as 1.0.0.  When I run it from source (i.e. building the package using instructions for Win/Linux) I'm seeing the proper behavior and version in the About dialog.

**Comment by robmadden** [comment]
I can confirm this. I've downloaded the binary several times and it shows versio 1.0.0 under "About".

**Comment by olivierandriessen** [comment]
Thanks for noticing, should be fixed now.
