### ISSUE TITLE
Add a way to edit/add more endpoints after creating a Project

### ISSUE THREAD

**Issue by lucasbento** [redound/graphql-ide#3]
I wanted to add a staging endpoint URL to a project and noticed that it currently doesn't have that option.

**Comment by olivierandriessen** [comment]
@lucasbento Since 0.1.4 you should be able to add more endpoints via the settings button

**Comment by lucasbento** [comment]
Oh, alright, that's cool.

Didn't see that button over there.

Thank you, @olivierandriessen!
