### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by kappuccino** [redound/graphql-ide#4]
I would like to display the error returned by graphql (like graphqli does)

when i request a query with a field not defined, the right panel stays empty

the only think that helps guessing, something is wrong is the field underlined in red and a bad request in the console...

this could be very usefull... to many people i guess

**Comment by olivierandriessen** [comment]
@kappuccino Thanks creating this issue. I also ran into this problem. I'm currently working on some major updates where this (and other inconveniences I noticed) will be solved. I'll leave this open and will let you know when it's fixed.

**Comment by kappuccino** [comment]
Hi @olivierandriessen thank you so much.
your tool is very usefull, the architecture by projet and saved queries are very very usefull

let me know if you want some feedback of those feature, I will be happy to help

**Comment by olivierandriessen** [comment]
@kappuccino Thanks! Well, in the coming update headers will be saved on the project level (currently on the query level), variables will be saved on the endpoint (environment) level (currently on the query level). Also, saving queries doesn't work always as expected and is not as intuitive as I want it to be. 

Are you using headers? If so, would you prefer to have query specific headers or would headers on the project level be enough (you could enable disable them using a checkbox)?

If you have any other feedback, let me know!

**Comment by kappuccino** [comment]
you're right about the saving queries mecanism... sometime the query is updated, sometime not... also i didn't find a way to create a new query, a button like "new query" should be great

In my opinion, headers should be query specific, but additionnal headers (from the project) should be added before theme. 
If i would like to redefine/unset a query, maybe i woulk like to enter "" as a value or find a way to disable one header for a particular query

I think projet + query header is a good match because, if you plan to use header for authentication for instance, you do not want to copy/past the same header for all your queries. for some queries maybe you want to add others headers...

good job, i hope my comments will help you to ship an even better app 👍

**Comment by olivierandriessen** [comment]
@kappuccino Really appreciate your feedback! I'm setting up tabs (kinda like browser tabs) to quickly switch between different queries, being able to select from history/stored queries. Add new query will be part of that, so that's going to be tackled. I agree with you on the headers. It would be ideal if we have project level headers that always apply to each query that gets executed as well as query level headers that merge on the project level ones. First, I'll probably add project level headers to quicken the release. Query headers then, can easily be added on the next run. 

Thanks for helping out. 👌

**Comment by olivierandriessen** [comment]
@kappuccino The list for 1.0 got bigger, so I've fixed this important issue in 0.1.5. You can follow the roadmap for 1.0 [here](https://github.com/redound/graphql-ide/pull/8)

**Comment by kappuccino** [comment]
Hello,
thank you very much. by the way, how queries & projects are stored... are they upgrade proof ?

**Comment by olivierandriessen** [comment]
@kappuccino Yes, they will be merged into the new data structure
