### ISSUE TITLE
Can't load GraphqlHub's schema

### ISSUE THREAD

**Issue by blackxored** [redound/graphql-ide#7]
Tried this for testing. It's unable to to load GraphqlHub's schema:

![](https://www.dropbox.com/s/d8ysq6ltv4gouv1/Screenshot%202016-12-02%2020.10.35.png?dl=1)

Queries do work thought, but documentation doesn't.

**Comment by olivierandriessen** [comment]
@blackxored This server is running a older version of graphql. It would be ideal GraphQL IDE could support older versions. Unless someone wants to look at it older versions wont be a priority for now.

**Comment by blackxored** [comment]
Oh I see. Well, will confirm when I get my server running. 👍
