### ISSUE TITLE
Does not supply project headers to request the schema json

### ISSUE THREAD

**Issue by karmajunkie** [redound/graphql-ide#9]
Using version 1.0.0, when set up my project with an authorization header, (in my case, a jwt token) then configure an environment pointed at my local development server, then click the "Refresh" link, the request is sent WITHOUT the header configured at the project config page. 

(Incidentally, it would be more useful to me to be able to configure headers per-environment than per-project, but that's a different ticket...)

What I expected was to see the authorization header listed in the request headers for the request when observing it in the web developer console network tab.

**Comment by olivierandriessen** [comment]
Thanks for pointing out, added environment level headers support too.

**Comment by karmajunkie** [comment]
Thanks for the quick fix, I really enjoy using the IDE!
